### ISSUE TITLE
Error on Add UAA SP configuration to UAA IdP

### ISSUE THREAD

**Issue by bisbos** [PredixDev/uaa-scripts#3]
Hi,

I am following the steps to configure SAML federation between UAA Service Provider (UAA SP) and UAA Identity Provider (UAA IdP)

On the Step 12,
./create-saml-sp.sh -n <uaa-sp-name> -m uaa-sp-metadata.xml -i

I am getting the error
uaac error
JSON::ParserError: 776: unexpected token at 'Invalid provider configuration.'

Could you please help me to resolve this issue

**Comment by irinaepshteyn** [comment]
Command you provided above to add service provider configuration is missing service provider name:
./create-saml-sp.sh -n **<uaa_sp_name>** -m uaa-sp-metadata.xml -i

**Comment by bisbos** [comment]
I executed it using the following command and getting the error
./create-saml-sp.sh -n testsp -m uaa-sp-metadata.xml -i

**Comment by bisbos** [comment]
I am executing UAA in docker container and using mysql DB to manage the users and clients

I downloaded the IDP metadata from the url (Docker Host is 192.168.99.100) http://192.168.99.100:8080/saml/idp/metadata

I downloaded the SP metadata (uaa-sp-metadata.xml) from the url http://192.168.99.100:8081/saml/metadata/cloudfoundry-saml-login

Then I executed the command ./create-saml-sp.sh -n testsp -m uaa-sp-metadata.xml -i

**Comment by irinaepshteyn** [comment]
Could you please provide SP metadata (uaa-sp-metadata.xml)

**Comment by bisbos** [comment]
<?xml version="1.0" encoding="UTF-8"?><md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="cloudfoundry-saml-login" entityID="cloudfoundry-saml-login"><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ds:Reference URI="#cloudfoundry-saml-login"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>Dgv27RSN+9+SN7buVcGpZqjTqfE=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>i2PLAAiDrrOuDVXRrUKy+N3tg8WhYvTPBeskfj5taoMXY1hFCb/g2qEhT6fOxLK6sE4sSCaQypSN84RsGCeol84Hre9V8aF6VguWx9ZOY4LGbF65DZVeB50V9mOvzDhO4zAcjE44fQdGOYLWgQtCBbOA1AqA1T+5PoD4Vgxx+II=</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIDSTCCArKgAwIBAgIBADANBgkqhkiG9w0BAQQFADB8MQswCQYDVQQGEwJhdzEOMAwGA1UECBMF
YXJ1YmExDjAMBgNVBAoTBWFydWJhMQ4wDAYDVQQHEwVhcnViYTEOMAwGA1UECxMFYXJ1YmExDjAM
BgNVBAMTBWFydWJhMR0wGwYJKoZIhvcNAQkBFg5hcnViYUBhcnViYS5hcjAeFw0xNTExMjAyMjI2
MjdaFw0xNjExMTkyMjI2MjdaMHwxCzAJBgNVBAYTAmF3MQ4wDAYDVQQIEwVhcnViYTEOMAwGA1UE
ChMFYXJ1YmExDjAMBgNVBAcTBWFydWJhMQ4wDAYDVQQLEwVhcnViYTEOMAwGA1UEAxMFYXJ1YmEx
HTAbBgkqhkiG9w0BCQEWDmFydWJhQGFydWJhLmFyMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKB
gQDHtC5gUXxBKpEqZTLkNvFwNGnNIkggNOwOQVNbpO0WVHIivig5L39WqS9u0hnA+O7MCA/KlrAR
4bXaeVVhwfUPYBKIpaaTWFQR5cTR1UFZJL/OF9vAfpOwznoD66DDCnQVpbCjtDYWX+x6imxn8HCY
xhMol6ZnTbSsFW6VZjFMjQIDAQABo4HaMIHXMB0GA1UdDgQWBBTx0lDzjH/iOBnOSQaSEWQLx1sy
GDCBpwYDVR0jBIGfMIGcgBTx0lDzjH/iOBnOSQaSEWQLx1syGKGBgKR+MHwxCzAJBgNVBAYTAmF3
MQ4wDAYDVQQIEwVhcnViYTEOMAwGA1UEChMFYXJ1YmExDjAMBgNVBAcTBWFydWJhMQ4wDAYDVQQL
EwVhcnViYTEOMAwGA1UEAxMFYXJ1YmExHTAbBgkqhkiG9w0BCQEWDmFydWJhQGFydWJhLmFyggEA
MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEEBQADgYEAYvBJ0HOZbbHClXmGUjGs+GS+xC1FO/am
2suCSYqNB9dyMXfOWiJ1+TLJk+o/YZt8vuxCKdcZYgl4l/L6PxJ982SRhc83ZW2dkAZI4M0/Ud3o
ePe84k8jm3A7EvH5wi5hvCkKRpuRBwn3Ei+jCRouxTbzKPsuCVB+1sNyxMTXzf0=</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><md:SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><md:KeyDescriptor use="signing"><ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:X509Data><ds:X509Certificate>MIIDSTCCArKgAwIBAgIBADANBgkqhkiG9w0BAQQFADB8MQswCQYDVQQGEwJhdzEOMAwGA1UECBMF
YXJ1YmExDjAMBgNVBAoTBWFydWJhMQ4wDAYDVQQHEwVhcnViYTEOMAwGA1UECxMFYXJ1YmExDjAM
BgNVBAMTBWFydWJhMR0wGwYJKoZIhvcNAQkBFg5hcnViYUBhcnViYS5hcjAeFw0xNTExMjAyMjI2
MjdaFw0xNjExMTkyMjI2MjdaMHwxCzAJBgNVBAYTAmF3MQ4wDAYDVQQIEwVhcnViYTEOMAwGA1UE
ChMFYXJ1YmExDjAMBgNVBAcTBWFydWJhMQ4wDAYDVQQLEwVhcnViYTEOMAwGA1UEAxMFYXJ1YmEx
HTAbBgkqhkiG9w0BCQEWDmFydWJhQGFydWJhLmFyMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKB
gQDHtC5gUXxBKpEqZTLkNvFwNGnNIkggNOwOQVNbpO0WVHIivig5L39WqS9u0hnA+O7MCA/KlrAR
4bXaeVVhwfUPYBKIpaaTWFQR5cTR1UFZJL/OF9vAfpOwznoD66DDCnQVpbCjtDYWX+x6imxn8HCY
xhMol6ZnTbSsFW6VZjFMjQIDAQABo4HaMIHXMB0GA1UdDgQWBBTx0lDzjH/iOBnOSQaSEWQLx1sy
GDCBpwYDVR0jBIGfMIGcgBTx0lDzjH/iOBnOSQaSEWQLx1syGKGBgKR+MHwxCzAJBgNVBAYTAmF3
MQ4wDAYDVQQIEwVhcnViYTEOMAwGA1UEChMFYXJ1YmExDjAMBgNVBAcTBWFydWJhMQ4wDAYDVQQL
EwVhcnViYTEOMAwGA1UEAxMFYXJ1YmExHTAbBgkqhkiG9w0BCQEWDmFydWJhQGFydWJhLmFyggEA
MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEEBQADgYEAYvBJ0HOZbbHClXmGUjGs+GS+xC1FO/am
2suCSYqNB9dyMXfOWiJ1+TLJk+o/YZt8vuxCKdcZYgl4l/L6PxJ982SRhc83ZW2dkAZI4M0/Ud3o
ePe84k8jm3A7EvH5wi5hvCkKRpuRBwn3Ei+jCRouxTbzKPsuCVB+1sNyxMTXzf0=</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:KeyDescriptor use="encryption"><ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:X509Data><ds:X509Certificate>MIIDSTCCArKgAwIBAgIBADANBgkqhkiG9w0BAQQFADB8MQswCQYDVQQGEwJhdzEOMAwGA1UECBMF
YXJ1YmExDjAMBgNVBAoTBWFydWJhMQ4wDAYDVQQHEwVhcnViYTEOMAwGA1UECxMFYXJ1YmExDjAM
BgNVBAMTBWFydWJhMR0wGwYJKoZIhvcNAQkBFg5hcnViYUBhcnViYS5hcjAeFw0xNTExMjAyMjI2
MjdaFw0xNjExMTkyMjI2MjdaMHwxCzAJBgNVBAYTAmF3MQ4wDAYDVQQIEwVhcnViYTEOMAwGA1UE
ChMFYXJ1YmExDjAMBgNVBAcTBWFydWJhMQ4wDAYDVQQLEwVhcnViYTEOMAwGA1UEAxMFYXJ1YmEx
HTAbBgkqhkiG9w0BCQEWDmFydWJhQGFydWJhLmFyMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKB
gQDHtC5gUXxBKpEqZTLkNvFwNGnNIkggNOwOQVNbpO0WVHIivig5L39WqS9u0hnA+O7MCA/KlrAR
4bXaeVVhwfUPYBKIpaaTWFQR5cTR1UFZJL/OF9vAfpOwznoD66DDCnQVpbCjtDYWX+x6imxn8HCY
xhMol6ZnTbSsFW6VZjFMjQIDAQABo4HaMIHXMB0GA1UdDgQWBBTx0lDzjH/iOBnOSQaSEWQLx1sy
GDCBpwYDVR0jBIGfMIGcgBTx0lDzjH/iOBnOSQaSEWQLx1syGKGBgKR+MHwxCzAJBgNVBAYTAmF3
MQ4wDAYDVQQIEwVhcnViYTEOMAwGA1UEChMFYXJ1YmExDjAMBgNVBAcTBWFydWJhMQ4wDAYDVQQL
EwVhcnViYTEOMAwGA1UEAxMFYXJ1YmExHTAbBgkqhkiG9w0BCQEWDmFydWJhQGFydWJhLmFyggEA
MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEEBQADgYEAYvBJ0HOZbbHClXmGUjGs+GS+xC1FO/am
2suCSYqNB9dyMXfOWiJ1+TLJk+o/YZt8vuxCKdcZYgl4l/L6PxJ982SRhc83ZW2dkAZI4M0/Ud3o
ePe84k8jm3A7EvH5wi5hvCkKRpuRBwn3Ei+jCRouxTbzKPsuCVB+1sNyxMTXzf0=</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8080/uaa/saml/SingleLogout/alias/cloudfoundry-saml-login"/><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:8080/uaa/saml/SingleLogout/alias/cloudfoundry-saml-login"/><md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName</md:NameIDFormat><md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8080/uaa/saml/SSO/alias/cloudfoundry-saml-login" index="0" isDefault="true"/><md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="http://localhost:8080/uaa/saml/SSO/alias/cloudfoundry-saml-login" index="1"/></md:SPSSODescriptor></md:EntityDescriptor>

**Comment by amiri-ge** [comment]
@bisbos Just a few extra questions?
1. It seems like you are federating UAA to itself on the same zone. Why are you doing this?
2. What is the error response you are getting from UAA? If you don't see one, modify the script by adding a "-v" to every curl command or "-t" to every uaac command in the script and please post the results.

**Comment by bisbos** [comment]
I am running separate instances of uaa for SP and IDP eventhough I am using the same zone uaa

The response I am getting with "-t" with uaac command
400 Bad Request
RESPONSE HEADERS:
  Server: Apache-Coyote/1.1
  Cache-Control: no-cache, no-store, max-age=0, must-revalidate
  Pragma: no-cache
  Expires: 0
  X-Xss-Protection: 1; mode=block
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Content-Type: application/json;charset=UTF-8
  Content-Length: 31
  Date: Tue, 03 May 2016 17:13:42 GMT
  Connection: close
RESPONSE BODY:
uaac error
JSON::ParserError: 776: unexpected token at 'Invalid provider configuration.'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/common.rb:155:in `parse'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/common.rb:155:in `parse'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cf-uaac-3.2.0/lib/cli/curl.rb:88:in `print_response'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cf-uaac-3.2.0/lib/cli/curl.rb:38:in `block in <class:CurlCli>'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cf-uaac-3.2.0/lib/cli/base.rb:272:in `block (2 levels) in run'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cf-uaac-3.2.0/lib/cli/base.rb:258:in `each'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cf-uaac-3.2.0/lib/cli/base.rb:258:in `block in run'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cf-uaac-3.2.0/lib/cli/base.rb:257:in `each'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cf-uaac-3.2.0/lib/cli/base.rb:257:in `run'
/Users/bbose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cf-uaac-3.2.0/bin/uaac:18:in `<top (required)>'
/Users/bbose/.rbenv/versions/2.2.3/bin/uaac:23:in `load'
/Users/bbose/.rbenv/versions/2.2.3/bin/uaac:23:in `<main>'

**Comment by irinaepshteyn** [comment]
@bisbos I added this issue to our board.  You could follow the progress here: https://rally1.rallydev.com/#/30377833713d/detail/userstory/55374590406
